### ISSUE TITLE
Install - Find Command (Asus GT-AX11000 fw:388.7_rog)

### ISSUE THREAD

**Issue by sam-the-not-so-wise** [jacklul/entware-pi-hole#1]
Hey Jaklul ! 

First off thank you so much for picking up this project!

I am on a slightly newer Busybox build than you are V1.25.1 so if this is an issue for a later date no worries ! 

when running the install from opkg, everything goes smooth until we hit the gravity setup 
then it throws an error on the find command 
___________________________________________________________________________________________________________________________________

Configuring pi-hole.
  [i] Running Pi-hole install/upgrade tasks...
  [✓] All required commands are available.
  [i] Setting random gravity update and updatechecker times...
  [i] Setting user and group in logrotate file...
find: unrecognized: -type
BusyBox v1.25.1 (2024-04-26 14:24:45 EDT) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
..
..
/opt/share/pihole/gravity.sh: line 359: syntax error: unexpected redirection

___________________________________________________________________________________________________________________________________

uname -a 

Linux Gimly 4.1.51 #4 SMP PREEMPT Fri Apr 26 15:26:38 EDT 2024 aarch64 ASUSWRT-Merlin
________________________________________________________________

**Comment by jacklul** [comment]
Well, it shouldn't even be using system's find as I added findutils to dependencies.
Perhaps $PATH does not prioritize /opt binaries ?
I will try to patch this later today.

**Comment by jacklul** [comment]
Please try installing **pi-hole-dev** package instead and tell me if it works

**Comment by sam-the-not-so-wise** [comment]
Absolute Wizard ! thank you so much !

that went off without a hitch !

_______________________
Configuring pi-hole-dev.
  [i] Running Pi-hole install/upgrade tasks...
  [i] Setting random gravity update and updatechecker times...
  [i] Setting user and group in logrotate file...
  [i] Creating new gravity database
  [i] Upgrading gravity database from version 18 to 19
  [i] Migrating content of /opt/etc/pihole/adlists.list into new database
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [✓] Creating new gravity databases
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 153902 exact domains and 0 ABP-style domains (blocking, ignored 0 non-domain entries)

  [✓] Building tree
  [i] Number of gravity domains: 153902 (153902 unique domains)
  [i] Number of exact denied domains: 0
  [i] Number of regex denied filters: 0
  [i] Number of exact allowed domains: 0
  [i] Number of regex allowed filters: 0
  [✓] Swapping databases
  [✓] The old database remains available
  [✓] Cleaning up stray matter

  [✓] Done.
_____________________________________________

**Comment by jacklul** [comment]
Great, I will merge the change into the main package soon
