### ISSUE TITLE
Support openwrt-23.05 on armv7l

### ISSUE THREAD

**Issue by nicerloop** [jacklul/entware-pi-hole#2]
Hi,

I have a Netgear Orbi RBK50 pair, and I would like to use OpenWrt with Pi-Hole.
These devices use an armv7l processor, and openwrt-23.05 can be installed on them.
https://openwrt.org/toh/hwdata/netgear/netgear_rbr50

I just tried to install your Pi-Hole packages and encountered these:

- [ ] architecture armv7l is not available
- [ ] signature file download failed
- [ ] package cron is not available
- [ ] package net-tools is not available

I tired to work around these and see how far I can get:
- use armv7sf-k3.2 architecture
- disable check_signature option

and finally I have been blocked: Package pi-hole version 2024.08.06-134720-c6ff1d52 has no valid architecture, ignoring. 

Can you help me contribute back the needed changes ?

**Comment by jacklul** [comment]
What prevents you from installing Entware on your device?
With this package I'm targeting Entware, not OpenWRT.

**Comment by nicerloop** [comment]
Hi,

I am just discovering the whole Entware/OpenWrt landscape...
I just added Entware sources to opkg to provide the missing packages.
`src/gz entware https://bin.entware.net/armv7sf-k3.2`

Still the install does not go further with many 'xxx has no valid architecture, ignoring.' messages, then fails: Unknown package 'pi-hole'.

I finally found https://github.com/Entware/Entware/wiki/Alternative-install-vs-standard, which installation type do you recommend for Pi-Hole?

**Comment by jacklul** [comment]
Entware != OpenWRT
The package repositories are not compatible

> which installation type do you recommend for Pi-Hole?

The standard one, alternative is only for specific scenarios

**Comment by nicerloop** [comment]
Thank you for you help and the good work you do and share. I will continue on discovering Entware and OpenWRT.
