### ISSUE TITLE
Router DNS settings?

### ISSUE THREAD

**Issue by hamensman** [jacklul/entware-pi-hole#4]
Using Asus RT-AX58U v2 running Asuswrt-Merlin [3004.388.8_2-gnuton1](https://github.com/gnuton/asuswrt-merlin.ng/releases/tag/3004.388.8_2-gnuton1).

So I can now access pi-hole on http://asusrouter.com:5080/admin :)

How would I change DNS settings on Asus router to force all traffic to pi-hole, since this is not a separate raspberry pi but instead _within_ the router?

**Comment by jacklul** [comment]
This should work: https://github.com/jacklul/entware-pi-hole/wiki/Installing-on-Asuswrt%E2%80%90Merlin
You just make the router advertise itself as the DNS, as far as I know you can use DNS director to force it in LAN.

**Comment by hamensman** [comment]
> This should work: https://github.com/jacklul/entware-pi-hole/wiki/Installing-on-Asuswrt%E2%80%90Merlin

I've done that section. In my case, changed `192.168.1.0/24` to `192.168.1.160` and `lan` to `eth0`.

> You just make the router advertise itself as the DNS

I have `Advertise router's IP in addition to user-specified DNS` set to `Yes`.

> you can use DNS director to force it in LAN.

Do I set `Global Redirection` to `Router`? What about a MAC address?

**Comment by jacklul** [comment]
> > you can use DNS director to force it in LAN.
> 
> Do I set `Global Redirection` to `Router`? What about a MAC address?

I never had Merlin firmware on my router so I don't exactly know what has to be set there, you might try asking about it on SNBforums. But I would say the global redirection is what you want.
